const fs = require('fs');
const path = require('path');

// Copy .htaccess to out directory
fs.copyFileSync(
  path.join(__dirname, '../.htaccess'),
  path.join(__dirname, '../out/.htaccess')
);

console.log('✅ .htaccess file copied to out directory');

// Validate XML sitemap files
function validateSitemapFile(filePath) {
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, 'utf8');
    if (!content.includes('<?xml version="1.0" encoding="UTF-8"?>')) {
      console.error(`❌ Invalid sitemap format in ${filePath}`);
      return false;
    }
    return true;
  }
  return false;
}

// Check and validate sitemap files
const sitemapFiles = [
  'sitemap.xml',
  'sitemap-services.xml',
  'sitemap-images.xml',
  'sitemap-index.xml'
];

const outDir = path.join(__dirname, '../out');
sitemapFiles.forEach(file => {
  const filePath = path.join(outDir, file);
  if (validateSitemapFile(filePath)) {
    console.log(`✅ ${file} validated successfully`);
  } else {
    console.warn(`⚠️ ${file} not found or invalid`);
  }
});

// robots.txt is generated by app/robots.ts, which already declares every
// sitemap. Verify rather than rewrite, so there is one owner of that file.
const robotsPath = path.join(outDir, 'robots.txt');
if (!fs.existsSync(robotsPath)) {
  console.warn('⚠️ robots.txt missing from out/ — check app/robots.ts');
} else {
  const robotsContent = fs.readFileSync(robotsPath, 'utf8');
  const missing = sitemapFiles.filter(file => !robotsContent.includes(`/${file}`));
  if (missing.length) {
    console.warn(`⚠️ robots.txt does not reference: ${missing.join(', ')}`);
  } else {
    console.log('✅ robots.txt references all sitemaps');
  }
}